version: '3.8'

services:
  codimd:
    image: hackmdio/hackmd:2.4.2-cjk@sha256:c79ce3277c9fdeb1b997aa86df773ba3b897f5810a1b17632101c3ea4326c7db
    hostname: codimd
    container_name: codimd__codimd
    restart: unless-stopped

    depends_on:
      - mariadb

    environment:
      CMD_DB_URL: mysql://codimd:codimd@mariadb:3306/codimd
      CMD_ALLOW_EMAIL_REGISTER: "false"
      CMD_DOMAIN: ${HOSTNAME}
      CMD_PROTOCOL_USESSL: "true"
      CMD_AUTO_VERSION_CHECK: "false"

    volumes:
      - type: volume
        source: codimd_data
        target: /home/hackmd/app/public/uploads

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      codimd_cloudflared:
      mariadb_codimd:

  mariadb:
    image: mariadb:11.0.3@sha256:7108b0cf6c4f23426d501606507e3417f44e3e31326b1cd5c8fe8ebea88a77a0
    hostname: mariadb
    container_name: codimd__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: codimd
      MYSQL_USER: codimd
      MYSQL_PASSWORD: codimd
      MYSQL_DATABASE: codimd

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      mariadb_codimd:

  cloudflared:
    image: cloudflare/cloudflared:2023.8.2@sha256:680085f76a59c53b7827a170d43dbdc9ef87235af6c39c9d4d028fde38359233
    hostname: cloudflared
    container_name: codimd__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      codimd_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - codimd__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  cloudflared_internet:
    name: codimd__cloudflared_internet

  codimd_cloudflared:
    name: codimd__codimd_cloudflared
    internal: true

  mariadb_codimd:
    name: codimd__mariadb_codimd
    internal: true

volumes:
  codimd_data:
    name: codimd__codimd_data

  mariadb_data:
    name: codimd__mariadb_data
