version: '3.8'

services:
  codimd:
    image: hackmdio/hackmd:2.4.2-cjk@sha256:659d5a4c1ae50d9a83cf911f7ff5f80f3055a6ab5d461d6aa7c13b0ecec37e24
    hostname: codimd
    container_name: codimd__codimd
    restart: unless-stopped

    depends_on:
      - mariadb

    environment:
      CMD_DB_URL: mysql://codimd:codimd@mariadb:3306/codimd
      CMD_ALLOW_EMAIL_REGISTER: "false"
      CMD_DOMAIN: ${HOSTNAME}
      CMD_PROTOCOL_USESSL: "true"
      CMD_AUTO_VERSION_CHECK: "false"

    volumes:
      - type: volume
        source: codimd_data
        target: /home/hackmd/app/public/uploads

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      codimd_cloudflared:
      mariadb_codimd:

  mariadb:
    image: mariadb:11.3.2@sha256:b5e508abc5d889425e90212541e30d29279b7ed34dd74bab5bb715b2f2aeeb7b
    hostname: mariadb
    container_name: codimd__mariadb
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: codimd
      MYSQL_USER: codimd
      MYSQL_PASSWORD: codimd
      MYSQL_DATABASE: codimd

    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      mariadb_codimd:

  cloudflared:
    image: cloudflare/cloudflared:2024.4.0@sha256:f2a8f348ad721b1a5f2836ca63c08d9a7629081e086a530c8b8bf05bc7fe0f01
    hostname: cloudflared
    container_name: codimd__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      codimd_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - codimd__cloudflared

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  cloudflared_internet:
    name: codimd__cloudflared_internet

  codimd_cloudflared:
    name: codimd__codimd_cloudflared
    internal: true

  mariadb_codimd:
    name: codimd__mariadb_codimd
    internal: true

volumes:
  codimd_data:
    name: codimd__codimd_data

  mariadb_data:
    name: codimd__mariadb_data
