version: '3.8'

services:
  codimd:
    image: hackmdio/hackmd:2.4.2-cjk
    hostname: codimd
    container_name: codimd__codimd
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      CMD_DB_URL: postgres://codimd:codimd@postgres/codimd
      CMD_USECDN: "true"
      CMD_ALLOW_EMAIL_REGISTER: "false"
      CMD_DOMAIN: ${HOSTNAME}
      CMD_PROTOCOL_USESSL: "true"
      CMD_AUTO_VERSION_CHECK: "false"

    volumes:
      - type: volume
        source: codimd_data
        target: /home/hackmd/app/public/uploads

    expose:
      - 3000

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      - outband

  postgres:
    image: postgres:17.4-alpine
    hostname: postgres
    container_name: codimd__postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: codimd
      POSTGRES_PASSWORD: codimd
      POSTGRES_DB: codimd

    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      - outband

  cloudflared:
    image: cloudflare/cloudflared:2025.4.0
    hostname: cloudflared
    container_name: codimd__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - outband

volumes:
  codimd_data:
    name: codimd__codimd_data

  postgres_data:
    name: codimd__postgres_data

networks:
  outband:
    name: codimd__outband